# Generated by Django 2.0.5 on 2018-05-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('latitud', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('longitud', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'escuelas',
                'db_table': 'escuelas',
            },
        ),
    ]
