# Generated by Django 2.0.5 on 2018-05-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0002_crear_usuario_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
                ('escuela', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='copatic.Escuela')),
            ],
            options={
                'verbose_name_plural': 'equipos',
                'db_table': 'equipos',
            },
        ),
    ]
