# Generated by Django 2.0.5 on 2018-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0003_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='eid',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
