# Generated by Django 2.0.5 on 2018-05-22 15:37

from django.db import migrations
from copatic.models.escuela import Escuela

def cargar_escuelas(apps, schema_editor):
    lista_de_escuelas = [
    ("Escuela Secundaria Nº32", "La Plata","-34.922162","-57.956888"),
    ("Escuela Media Nº28","La Plata","-34.853378", "-58.074829"),
    ("Escuela Secundaria Nº34",	"La Plata",	"-34.920183", "-57.945369"),
    ("Escuela Secundaria Nº27",	"La Plata",	"-34.912375", "-57.975525"),
    ("Escuela Secundaria Nº31",	"La Plata",	"-34.9079902","-57.9482935"),
    ("Escuela Secundaria Nº44",	"La Plata",	"-34.9402514","-57.9406519"),
    ("Escuela Secundaria  Nº 67",	"La Plata",	"-34.874026", "-58.106335"),
    ("Escuela Secundaria Nº62",	"La Plata",	"-34.9268591","-57.9542722"),
    ("Escuela Secundaria Nº56",	"La Plata",	"-34.9371643","-57.9532363"),
    ("Escuela Secundaria Nº18",	"Avellaneda",	"-34.6606816","-58.3689846"),
    ("Escuela Secundaria Nº11",	"Lanús",	"-34.7316826","-58.3518904"),
    ("Escuela Secundaria Nº1",	"La Matanza",	"-34.7010128","-58.630718"),
    ("Escuela Secundaria Nº6",	"Esteban Echeverria",	"-34.8177835","-58.4390154"),
    ("Escuela Secundaria Nº2",	"San Fernando",	"-34.4671091","-58.5730771"),
    ("Escuela Secundaria Nº12",	"San Fernando",	"-34.4417425","-58.5574137"),
    ("Escuela Secundaria Nº13",	"San Fernando",	"-34.4522287","-58.5407646"),
    ("Escuela Secundaria Nº14",	"San Fernando",	"-34.4726608","-58.5948578"),
    ("Escuela Secundaria Nº23",	"San Fernando",	"-34.4442506","-58.5509528"),
    ("Escuela Secundaria Nº24",	"San Fernando",	"-34.4586768","-58.5604972"),
    ("Escuela Secundaria Basica Nº14",	"San Fernando",	"-34.44051","-58.563843"),
    ("Escuela Secundaria Nº4",	"San Isidro",	"-34.5094243","-58.5699192"),
    ("Escuela Secundaria Nº14",	"San Isidro",	"-34.5031394","-58.5696888"),
    ("Escuela Secundaria Nº2",	"San Isidro",	"-34.5220102","-58.5453037"),
    ("Escuela Secundaria Nº7",	"San Isidro",	"-34.5086136","-58.5379955"),
    ("Escuela Secundaria Nº9",	"San Isidro",	"-34.4964543","-58.525099"),
    ("Escuela Secundaria Nº7",	"Tigre",	"-34.4193377","-58.6024488"),
    ("Escuela Técnica Nº1",	"Tigre",	"-34.4687695","-58.6436001"),
    ("Escuela Secundaria Nº19",	"Tigre",	"-34.4552944","-58.6140683"),
    ("Escuela Secundaria Basica Nº26",	"Tigre",	"-34.4374591","-58.5798509"),
    ("Escuela Secundaria Basica Nº2",	"Tigre",	"-34.4336221","-58.5691171"),
    ("Escuela Secundaria Nº9",	"Tigre",	"-34.418611", "-58.588149"),
    ("Escuela Secundaria Nº4",	"Vicente López",	"-34.5331056","-58.477578"),
    ("Escuela Secundaria Nº3",	"Vicente López",	"-34.5273819","-58.5349094"),
    ("Escuela Secundaria Nº22",	"General San Martín",	"-34.5544368","-58.5625536"),
    ("Escuela Secundaria Nº1",	"General San Martín",	"-34.5794331","-58.5325533"),
    ("Escuela Técnica Nº3",	"General San Martín",	"-34.5788219","-58.5444672"),
    ("Escuela Técnica Nº4",	"General San Martín",	"-34.579962","-58.5351223"),
    ("Secundaria Basica Nº17 (EES 46)",	"General San Martín",	"-34.5367846","-58.5823862"),
    ("Escuela Secundaria Nº2",	"Hurlingham",	"-34.6106139","-58.643569"),
    ("Escuela Técnica Nº2",	"Hurlingham",	"-34.5942984","-58.6245306"),
    ("Escuela Secundaria Basica Nº3",	"Hurlingham",	"-34.5886456","-58.6577108"),
    ("Escuela Secundaria Nº7",	"Hurlingham",	"-34.6264436","-58.6512223"),
    ("Escuela Secundaria Nº19",	"Tres de Febrero",	"-34.5889677","-58.5981388"),
    ("Escuela Secundaria Nº7",	"Merlo",	"-34.6686822","-58.7560132"),
    ("Escuela Secundaria Nº43",	"Merlo",	"-34.6868077","-58.6804529"),
    ("Escuela Secundaria Basica Nº3",	"Malvinas Argentinas",	"-34.4979276","-58.6934336"),
    ("Escuela Secundaria Basica Nº19",	"San Miguel",	"-34.5663127","-58.731916"),
    ("Escuela Secundaria Nº15",	"Escobar",	"-34.3997045","-58.7771197"),
    ("Escuela Secundaria Nº13",	"Escobar",	"-34.414909", "-58.767782"),
    ("Escuela Secundaria Basica Nº18",	"Pilar",	"-34.4767608","-58.8370098"),
    ("Escuela Secundaria Nº4",	"Rojas",	"-34.202969", "-60.734800"),
    ("Anexo Escuela Secundaria Nº7",	"Chacabuco",	"-34.627129", "-60.477290"),
    ("Escuela Secundaria Nº6",	"Bragado",	"-35.11721","-60.4743911"),
    ("Escuela Secundaria Nº5",	"Pehuajó",	"-35.8027545","-61.8918456"),
    ("Escuela Técnica Nº1",	"Pinamar",	"-37.114129", "-56.883881"),
    ("Escuela Secundaria Nº3",	"Bahía Blanca",	"-38.7119703","-62.2789569"),
    ("Escuela Secundaria Nº24",	"Bahía Blanca",	"-38.6985539","-62.2711998"),
    ("Escuela Secundaria Técnica 1",	"Monte Hermoso",	"-38.9803121","-61.3111816"),
    ("Escuela Secundaria Nº 3",	"Las Flores",	"-36.0136184","-59.10004"),
    ("Escuela Secundaria Nº2",	"Lobos",	"-35.3009866","-59.1692581"),
    ("Escuela Secundaria Nº5",	"Lobos",	"-35.171190", "-59.091740"),
    ("Escuela Secundaria N°33",	"Florencio Varela",	"-34.8024502","-58.2651732"),
    ("Escuela Secundaria N°20",	"Luján", "-34.575693", "-59.104633"),
    ("Escuela Secundaria Técnica N°4",	"San Nicolás",	"-33.3224857","-60.2290963"),
    ("Escuela Secundaria N°2","Salliqueló", "-36.744326", "-62.959678"),
    ("Escuela Secundaria N°4","General Paz", "-34.593385", "-58.626772"),
    ("Escuela Secundaria N°61","General Pueyrredón","-37.950920","-57.577747"),
    ("Escuela Secundaria N°1","Necochea",	"-38.5534141","-58.7376221"),
    ("Escuela Secundaria N°2","Tres Arroyos",	"-38.3756327","-60.2761255"),
    ("Escuela Secundaria N°2","Carhué", "-37.183533", "-62.762515"),
    ("Escuela Secundaria N°13","Olavarría", "-36.921453", "-60.295844"),
    ]
    for escuela in lista_de_escuelas:
        Escuela.objects.create(nombre=escuela[0], localidad=escuela[1], latitud=escuela[2], longitud=escuela[3])

class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0004_equipo_eid'),
    ]

    operations = [
        migrations.RunPython(cargar_escuelas, migrations.RunPython.noop),
    ]
