# Generated by Django 2.0.5 on 2018-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0005_cargar_escuelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='a10estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a10link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a11estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a11link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a12estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a12link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a13estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a13link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a14estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a14link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a15estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a15link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a16estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a16link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a1estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a1link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a2estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a2link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a3estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a3link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a4estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a4link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a5estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a5link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a6estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a6link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a7estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a7link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a8estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a8link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a9estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='a9link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
