# Generated by Django 2.0.5 on 2018-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0007_cargar_equipos_vacios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fase', models.IntegerField(default=None)),
                ('puntos', models.IntegerField(default=None)),
                ('descripcion', models.TextField(default=None)),
            ],
            options={
                'verbose_name_plural': 'actividades',
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.CharField(default=None, max_length=100))
            ],
            options={
                'verbose_name_plural': 'insignias',
                'db_table': 'insignias',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='insignias',
            field=models.ManyToManyField(blank=True, default=None, related_name='actividades', to='copatic.Insignia'),
        ),
    ]
