# Generated by Django 2.0.5 on 2018-05-29 19:42

from django.db import migrations
from copatic.models.insignia import Insignia

def crear_insignias(apps, schema_editor):
    lista_de_insignias = [
        ("Estética y diseño"),
        ("Producción escrita"),
        ("Producción fotográfica"),
        ("Producción audiovisual"),
        ("Producción sonora"),
        ("Producción multimedia"),
        ("Programación"),
        ("Participación en redes sociales"),
        ("Trabajo colaborativo"),
        ("Gestión de información"),
        ("Actuación"),
        ("Evaluación y selección de medios y tecnologías"),
        ("Interpretación textual"),
        ("Prevención"),
    ]

    for insignia in lista_de_insignias:
        Insignia.objects.create(nombre=insignia[0])

class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0008_auto_20180529_1942'),
    ]

    operations = [
        migrations.RunPython(crear_insignias, migrations.RunPython.noop),
    ]
