# Generated by Django 2.0.5 on 2018-05-29 19:42

from django.db import migrations
from copatic.models.insignia import Insignia

def crear_insignias(apps, schema_editor):
    lista_de_insignias = [
        ("Estética y diseño","estetica-y-diseno"),
        ("Producción escrita","produccion-escrita"),
        ("Producción fotográfica","produccion-fotografica"),
        ("Producción audiovisual","produccion-audiovisual"),
        ("Producción sonora","produccion-sonora"),
        ("Producción multimedia","produccion-multimedia"),
        ("Programación","programacion"),
        ("Participación en redes sociales","participacion-en-redes-sociales"),
        ("Trabajo colaborativo","trabajo-colaborativo"),
        ("Gestión de información","gestion-de-informacion"),
        ("Actuación","actuacion"),
        ("Evaluación y selección de medios y tecnologías","evaluacion-y-seleccion-de-medios-y-tecnologias"),
        ("Interpretación textual","interpretacion-textual")
    ]

    for insignia in lista_de_insignias:
        Insignia.objects.create(nombre=insignia[0], slug=insignia[1])

class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0008_auto_20180529_1942'),
    ]

    operations = [
        migrations.RunPython(crear_insignias, migrations.RunPython.noop),
    ]
