# Generated by Django 2.0.5 on 2018-05-29 19:42

from django.db import migrations
from copatic.models.actividad import Actividad
from copatic.models.insignia import Insignia

def crear_actividades(apps, schema_editor):
    lista_de_actividades = [
        ("Mapa interactivo Rusia 2018","1","3","",[("Producción multimedia")]),
        ("Hay equipo","1","3","",[("Estética y diseño")]),
        ("Crónica: el Mundial en mi escuela","1","3","",[("Producción escrita")]),
        ("El campeón inesperado","1","5","",[("Actuación")]),
        ("De cábalas y otras yerbas","2","5","",[("Trabajo colaborativo")]),
        ("El Mundial '78 en primera persona","2","3","",""),
        ("El ranking de las proteínas","2","5","",[("Gestión de información")]),
        ("Remix  Mundial","2","3","",[("Producción audiovisual")]),
        ("¿A qué jugamos?","3","3","",""),
        ("Al ritmo del Mundial","3","4","",[("Producción sonora")]),
        ("El fútbol en mi barrio","3","4","",[("Producción fotográfica")]),
        ("Campaña contra la discriminación de género en el fútbol","3","5","",[("Participación en redes sociales")]),
        ("El gol animado","4","5","",[("Programación")]),
        ("Medios, fútbol y discriminación","4","4","",[("Evaluación y selección de medios y tecnologías"),( "Interpretación textual")]),
        ("El Mundial de los datos","4","4","",""),
        ("Los estadios a través de la historia","4","4","",""),
    ]

    for actividad in lista_de_actividades:
        a = Actividad.objects.create(titulo=actividad[0], fase=actividad[1],puntos=actividad[2],descripcion=actividad[3])
        for insignia in actividad[4]:
            i = Insignia.objects.get(nombre=insignia)
            a.insignias.add(i)
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0009_crear_insignias'),
    ]

    operations = [
        migrations.RunPython(crear_actividades, migrations.RunPython.noop),
    ]
