# Generated by Django 2.0.5 on 2018-05-29 19:42

from django.db import migrations
from copatic.models.actividad import Actividad

def crear_actividades(apps, schema_editor):
    lista_de_actividades = [
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
        ("","","",""),
    ]

    for actividad in lista_de_actividades:
        Actividad.objects.create(titulo=actividad[0], fase=actividad[1],puntos=actividad[2],descripcion=actividad[3])

class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0009_crear_actividades'),
    ]

    operations = [
        migrations.RunPython(crear_actividades, migrations.RunPython.noop),
    ]
