# Generated by Django 2.0.5 on 2018-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0010_crear_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'etapas',
                'db_table': 'etapas',
            },
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['eid'], 'verbose_name_plural': 'equipos'},
        ),
    ]
