# Generated by Django 2.0.5 on 2018-06-14 14:50

from django.db import migrations
from copatic.models.fase import Fase

def crear_fases(apps, schema_editor):
    lista_de_fases = [
        ("0",True),
        ("1",True),
        ("2",False),
        ("3",False),
        ("4",False),
    ]

    for fase in lista_de_fases:
        Fase.objects.create(nombre=fase[0], estado=fase[1])

class Migration(migrations.Migration):

    dependencies = [
        ('copatic', '0011_auto_20180614_1449'),
    ]

    operations = [
        migrations.RunPython(crear_fases, migrations.RunPython.noop),
    ]
