from django.db import models

class Equipo(models.Model):
    escuela = models.ForeignKey('Escuela', on_delete=models.CASCADE, related_name='equipos', default=None, blank=True, null=True)
    eid = models.CharField(max_length=4, default=None, blank=True, null=True)
    nombre = models.CharField(max_length=100)
    dt = models.CharField(max_length=100)
    puntos = models.IntegerField(default=0)

    a1estado = models.BooleanField(default=False)
    a1titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a1descripcion = models.TextField(default=None, blank=True, null=True)
    a1link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a2estado = models.BooleanField(default=False)
    a2titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a2descripcion = models.TextField(default=None, blank=True, null=True)
    a2link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a3estado = models.BooleanField(default=False)
    a3titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a3descripcion = models.TextField(default=None, blank=True, null=True)
    a3link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a4estado = models.BooleanField(default=False)
    a4titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a4descripcion = models.TextField(default=None, blank=True, null=True)
    a4link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a5estado = models.BooleanField(default=False)
    a5titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a5descripcion = models.TextField(default=None, blank=True, null=True)
    a5link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a6estado = models.BooleanField(default=False)
    a6titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a6descripcion = models.TextField(default=None, blank=True, null=True)
    a6link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a7estado = models.BooleanField(default=False)
    a7titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a7descripcion = models.TextField(default=None, blank=True, null=True)
    a7link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a8estado = models.BooleanField(default=False)
    a8titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a8descripcion = models.TextField(default=None, blank=True, null=True)
    a8link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a9estado = models.BooleanField(default=False)
    a9titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a9descripcion = models.TextField(default=None, blank=True, null=True)
    a9link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a10estado = models.BooleanField(default=False)
    a10titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a10descripcion = models.TextField(default=None, blank=True, null=True)
    a10link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a11estado = models.BooleanField(default=False)
    a11titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a11descripcion = models.TextField(default=None, blank=True, null=True)
    a11link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a12estado = models.BooleanField(default=False)
    a12titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a12descripcion = models.TextField(default=None, blank=True, null=True)
    a12link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a13estado = models.BooleanField(default=False)
    a13titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a13descripcion = models.TextField(default=None, blank=True, null=True)
    a13link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a14estado = models.BooleanField(default=False)
    a14titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a14descripcion = models.TextField(default=None, blank=True, null=True)
    a14link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a15estado = models.BooleanField(default=False)
    a15titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a15descripcion = models.TextField(default=None, blank=True, null=True)
    a15link = models.CharField(max_length=100,default=None, blank=True, null=True)
    a16estado = models.BooleanField(default=False)
    a16titulo = models.CharField(max_length=100,default=None, blank=True, null=True)
    a16descripcion = models.TextField(default=None, blank=True, null=True)
    a16link = models.CharField(max_length=100,default=None, blank=True, null=True)

    class Meta:
        db_table = 'equipos'
        verbose_name_plural = "equipos"

    class JSONAPIMeta:
        resource_name = 'equipos'
